stages:
  - build
  - build:docker
  - build:deploy
  - test
  - sync

variables:
  GROUP_ID: cn.com.xuxiaowei.shield
  ARTIFACT_ID: gateway
  VERSION: 0.0.1-SNAPSHOT
  CI_JAVA_OPTS: -Xms256m -Xmx512m

include:
  - local: .gitlab/ci/build.yml
  - local: .gitlab/ci/build-docker.yml
  - local: .gitlab/ci/build-deploy.yml
  - local: .gitlab/ci/build-deploy-g150s.yml
  - local: .gitlab/ci/build-deploy-911k.yml
  - local: .gitlab/ci/ultimate.yml
  - local: .gitlab/ci/sync.yml
