services:
  gateway-shield-docs:
    image: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/gateway-shield-docs:${DOCKER_TAG}-${CI_PIPELINE_ID}
    restart: always
    ports:
      - ${GATEWAY_SHIELD_DOCS_PORT:-45850}:80
    volumes:
      - /gateway-shield-docs/logs:/var/log/nginx
    container_name: gateway-shield-docs
