server:
  port: ${GATEWAY_SHIELD_PORT:45450}
  # forward-headers-strategy: NATIVE
  tomcat:
    # https://docs.spring.io/spring-boot/how-to/webserver.html#howto.webserver.use-behind-a-proxy-server.tomcat
    remoteip:
      # 从中提取远程IP的HTTP标头的名称。 例如，`X-FORWARDED-FOR`。
      remote-ip-header: X-Real-IP
      # 用于覆盖原始端口值的HTTP标头的名称。
      port-header: X-Forwarded-Proto

---

gateway-shield:
  http-port: ${GATEWAY_SHIELD_PORT_HTTP:45455}
  refresh-routes-event-path: ${GATEWAY_SHIELD_ROUTES_PATH:}

---

spring:
  application:
    name: gateway-shield

---

spring:
  data:
    redis:
      host: ${GATEWAY_SHIELD_REDIS_HOST:127.0.0.1}
      port: ${GATEWAY_SHIELD_REDIS_PORT:6379}
      database: ${GATEWAY_SHIELD_REDIS_DATABASE:8}
      password: ${GATEWAY_SHIELD_REDIS_PASSWORD:xuxiaowei.com.cn}

---

spring:
  cloud:
    gateway:
      redis-route-definition-repository:
        enabled: ${GATEWAY_SHIELD_REDIS_ROUTE:false}

---

spring:
  datasource:
    url: jdbc:p6spy:mysql://${GATEWAY_SHIELD_DATABASE_HOST:127.0.0.1}:${GATEWAY_SHIELD_DATABASE_PORT:3306}/${GATEWAY_SHIELD_DATABASE:gateway_shield}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: ${GATEWAY_SHIELD_DATABASE_USERNAME:root}
    password: ${GATEWAY_SHIELD_DATABASE_PASSWORD:xuxiaowei.com.cn}

logging:
  level:
    cn.com.xuxiaowei: debug
    # 记录请求地址、转发目的地
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug
    # 异常日志
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: debug
    # 当前应用响应数据（非转发数据）
    org.springframework.core.codec.CharSequenceEncoder: debug
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{G-Request-Id} %clr(:){faint} %X{G-Host} %clr(:){faint} %X{G-Host-Name} %clr(:){faint} %X{G-Host-Address} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %X{G-Request-Id} : %X{G-Host} : %X{G-Host-Name} : %X{G-Host-Address} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: /logs/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 365
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log.gz
